yaf.lo: /Users/wc/Sites/www/yaf/yaf.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/yaf.c -o yaf.lo 
yaf_application.lo: /Users/wc/Sites/www/yaf/yaf_application.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/yaf_application.c -o yaf_application.lo 
yaf_bootstrap.lo: /Users/wc/Sites/www/yaf/yaf_bootstrap.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/yaf_bootstrap.c -o yaf_bootstrap.lo 
yaf_dispatcher.lo: /Users/wc/Sites/www/yaf/yaf_dispatcher.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/yaf_dispatcher.c -o yaf_dispatcher.lo 
yaf_exception.lo: /Users/wc/Sites/www/yaf/yaf_exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/yaf_exception.c -o yaf_exception.lo 
yaf_config.lo: /Users/wc/Sites/www/yaf/yaf_config.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/yaf_config.c -o yaf_config.lo 
configs/yaf_config_ini.lo: /Users/wc/Sites/www/yaf/configs/yaf_config_ini.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/configs/yaf_config_ini.c -o configs/yaf_config_ini.lo 
configs/yaf_config_simple.lo: /Users/wc/Sites/www/yaf/configs/yaf_config_simple.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/configs/yaf_config_simple.c -o configs/yaf_config_simple.lo 
yaf_request.lo: /Users/wc/Sites/www/yaf/yaf_request.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/yaf_request.c -o yaf_request.lo 
requests/yaf_request_http.lo: /Users/wc/Sites/www/yaf/requests/yaf_request_http.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/requests/yaf_request_http.c -o requests/yaf_request_http.lo 
requests/yaf_request_simple.lo: /Users/wc/Sites/www/yaf/requests/yaf_request_simple.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/requests/yaf_request_simple.c -o requests/yaf_request_simple.lo 
yaf_response.lo: /Users/wc/Sites/www/yaf/yaf_response.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/yaf_response.c -o yaf_response.lo 
responses/yaf_response_http.lo: /Users/wc/Sites/www/yaf/responses/yaf_response_http.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/responses/yaf_response_http.c -o responses/yaf_response_http.lo 
responses/yaf_response_cli.lo: /Users/wc/Sites/www/yaf/responses/yaf_response_cli.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/responses/yaf_response_cli.c -o responses/yaf_response_cli.lo 
yaf_view.lo: /Users/wc/Sites/www/yaf/yaf_view.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/yaf_view.c -o yaf_view.lo 
views/yaf_view_interface.lo: /Users/wc/Sites/www/yaf/views/yaf_view_interface.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/views/yaf_view_interface.c -o views/yaf_view_interface.lo 
views/yaf_view_simple.lo: /Users/wc/Sites/www/yaf/views/yaf_view_simple.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/views/yaf_view_simple.c -o views/yaf_view_simple.lo 
yaf_controller.lo: /Users/wc/Sites/www/yaf/yaf_controller.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/yaf_controller.c -o yaf_controller.lo 
yaf_action.lo: /Users/wc/Sites/www/yaf/yaf_action.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/yaf_action.c -o yaf_action.lo 
yaf_router.lo: /Users/wc/Sites/www/yaf/yaf_router.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/yaf_router.c -o yaf_router.lo 
routes/yaf_route_interface.lo: /Users/wc/Sites/www/yaf/routes/yaf_route_interface.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/routes/yaf_route_interface.c -o routes/yaf_route_interface.lo 
routes/yaf_route_static.lo: /Users/wc/Sites/www/yaf/routes/yaf_route_static.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/routes/yaf_route_static.c -o routes/yaf_route_static.lo 
routes/yaf_route_simple.lo: /Users/wc/Sites/www/yaf/routes/yaf_route_simple.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/routes/yaf_route_simple.c -o routes/yaf_route_simple.lo 
routes/yaf_route_supervar.lo: /Users/wc/Sites/www/yaf/routes/yaf_route_supervar.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/routes/yaf_route_supervar.c -o routes/yaf_route_supervar.lo 
routes/yaf_route_regex.lo: /Users/wc/Sites/www/yaf/routes/yaf_route_regex.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/routes/yaf_route_regex.c -o routes/yaf_route_regex.lo 
routes/yaf_route_rewrite.lo: /Users/wc/Sites/www/yaf/routes/yaf_route_rewrite.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/routes/yaf_route_rewrite.c -o routes/yaf_route_rewrite.lo 
routes/yaf_route_map.lo: /Users/wc/Sites/www/yaf/routes/yaf_route_map.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/routes/yaf_route_map.c -o routes/yaf_route_map.lo 
yaf_loader.lo: /Users/wc/Sites/www/yaf/yaf_loader.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/yaf_loader.c -o yaf_loader.lo 
yaf_registry.lo: /Users/wc/Sites/www/yaf/yaf_registry.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/yaf_registry.c -o yaf_registry.lo 
yaf_plugin.lo: /Users/wc/Sites/www/yaf/yaf_plugin.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/yaf_plugin.c -o yaf_plugin.lo 
yaf_session.lo: /Users/wc/Sites/www/yaf/yaf_session.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/wc/Sites/www/yaf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/wc/Sites/www/yaf/yaf_session.c -o yaf_session.lo 
$(phplibdir)/yaf.la: ./yaf.la
	$(LIBTOOL) --mode=install cp ./yaf.la $(phplibdir)

./yaf.la: $(shared_objects_yaf) $(YAF_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_yaf) $(YAF_SHARED_LIBADD)

